# Generated by Django 4.2.9 on 2024-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_step_tracker_gql", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
