# Generated by Django 4.2.9 on 2024-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_step_tracker_gql", "0002_alter_recipestep_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
